version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["/bin/sh", "-c", "tail -f /dev/null"]
    env_file: .env
    stdin_open: true
    tty: true
    volumes:
      - ./app:/app
