version: '3.4'

services:
  app:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: techlish
    env_file: .env
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
