version: 2.1

jobs:
  deploy:
    docker:
    - image: google/cloud-sdk:alpine
    environment:
      PROJECT: "techlish"
      FUNCTION_NAME: "bot"
      ENTRY_POINT: "handle_cloud_functions"
      RUNTIME: "python37"
      TRIGGER_EVENT: "providers/cloud.pubsub/eventTypes/topic.publish"
      TRIGGER_RESOURCE: "twiceaday"
      REGION: "us-central1"
      MEMORY: "256MB"
      TIMEOUT: "60s"
    steps:
    - checkout
    - run:
        name: Prepare
        command: |
          apk --no-cache add zip
    - run:
        name: Zip scripts
        command: |
          zip functions -r ./app
    - run:
        name: Authorize gcloud
        command: |
          echo $SERVICE_ACCOUNT_KEY | base64 -d | \
            gcloud auth activate-service-account --key-file=-
    - run:
        name: Deploy to Google Cloud Functions
        command: |
          echo $ENV_FILE | base64 -d > .env.yaml
          gcloud functions deploy $FUNCTION_NAME \
            --entry-point $ENTRY_POINT \
            --runtime $RUNTIME \
            --trigger-event $TRIGGER_EVENT \
            --trigger-resource $TRIGGER_RESOURCE \
            --source ./app/ \
            --env-vars-file .env.yaml \
            --project $PROJECT \
            --region $REGION \
            --memory $MEMORY \
            --timeout $TIMEOUT
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - deploy:
        filters:
          branches:
            only:
              - master
